### ISSUE TITLE
Error creating push database! { Error: You are not a server admin.

### ISSUE THREAD

**Issue by AkhilMannuru** [HospitalRun/hospitalrun-server#109]
Error creating push database! { Error: You are not a server admin.
    at Request._callback (/usr/src/app/node_modules/nano/lib/nano.js:252:15)
    at Request.self.callback (/usr/src/app/node_modules/nano/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/src/app/node_modules/nano/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/nano/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
  name: 'Error',
  error: 'unauthorized',
  reason: 'You are not a server admin.',
  scope: 'couch',
  statusCode: 401,
  request: 
   { method: 'PUT',
     headers: 
      { 'content-type': 'application/json',
        accept: 'application/json' },
     uri: 'http://XXXXXX:XXXXXX@couchdb:5984/pushinfo' },
  headers: 
   { date: 'Fri, 15 Jun 2018 06:03:13 GMT',
     'content-type': 'application/json',
     'cache-control': 'must-revalidate',
     statusCode: 401,
     uri: 'http://XXXXXX:XXXXXX@couchdb:5984/pushinfo' },
  errid: 'non_200',
  description: 'couch returned 401' }

**Comment by stukalin** [comment]
Sorry, but that's very unclear. What did you do, what had you done?

**Comment by AkhilMannuru** [comment]
Problem solved, Thanks :)

**Comment by donaldwasserman** [comment]
For future googlers: 

I think this is caused from trying to access the containers outside of the internal docker services or bad username/password. 

(I think).
