### ISSUE TITLE
Error in Hospital Run Docker Container

### ISSUE THREAD

**Issue by mjibril** [HospitalRun/hospitalrun-server#117]
I cannot seem to be able to start the hospitalrun docker container. This is the output after an attach.

`$ docker attach  hospitalrun  

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    70  100    64  100     6   5991    561 --:--:-- --:--:-- --:--:--  6400
{"error":"unauthorized","reason":"You are not a server admin."}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   106  100    12  100    94    117    917 --:--:-- --:--:-- --:--:--   912
{"ok":true}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    95  100    95    0     0   4414      0 --:--:-- --:--:-- --:--:--  4523
{"error":"file_exists","reason":"The database could not be created, the file already exists."}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    99  100    12  100    87    107    776 --:--:-- --:--:-- --:--:--   783
{"ok":true}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   224  100    58  100   166   2369   6781 --:--:-- --:--:-- --:--:--  7217
{"error":"conflict","reason":"Document update conflict."}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    95  100    95    0     0   6134      0 --:--:-- --:--:-- --:--:--  6785
{"error":"file_exists","reason":"The database could not be created, the file already exists."}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   105  100    12  100    93     95    740 --:--:-- --:--:-- --:--:--   744
{"ok":true}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1075  100    58  100  1017    933  16362 --:--:-- --:--:-- --:--:-- 16672
{"error":"conflict","reason":"Document update conflict."}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   413  100   207  100   206   9545   9499 --:--:-- --:--:-- --:--:--  9857
"{couch_httpd_oauth, oauth_authentication_handler}, {couch_httpd_auth, proxy_authentification_handler}, {couch_httpd_auth, cookie_authentication_handler}, {couch_httpd_auth, default_authentication_handler}"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13  100     7  100     6    166    142 --:--:-- --:--:-- --:--:--   170
"true"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   183  100    58  100   125   1866   4023 --:--:-- --:--:-- --:--:--  4166
{"error":"conflict","reason":"Document update conflict."}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    60  100    58  100     2   1841     63 --:--:-- --:--:-- --:--:--  1870
{"error":"conflict","reason":"Document update conflict."}
Setting up mappings
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1516  100   351  100  1165   2652   8805 --:--:-- --:--:-- --:--:--  8893
{"error":{"root_cause":[{"type":"index_already_exists_exception","reason":"index [hrdb/3ILqac3_Qay1jc4vGu6nZA] already exists","index_uuid":"3ILqac3_Qay1jc4vGu6nZA","index":"hrdb"}],"type":"index_already_exists_exception","reason":"index [hrdb/3ILqac3_Qay1jc4vGu6nZA] already exists","index_uuid":"3ILqac3_Qay1jc4vGu6nZA","index":"hrdb"},"status":400}TypeError: Cannot read property 'emit' of null
    at Socket.socketCloseListener (_http_client.js:277:6)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:509:12)

npm ERR! Linux 4.15.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! hospitalrun-server@1.0.0-beta start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hospitalrun-server@1.0.0-beta start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hospitalrun-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hospitalrun-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hospitalrun-server
npm ERR! There is likely additional logging output above.
`

**Comment by donaldwasserman** [comment]
@mjibril Sorry for the delay about getting back with you. 

What do you have set as your `config.js`? 

You need to create a new `config.js` based on the values in `config-example.js`
