### ISSUE TITLE
Hospitalrun-server's npm start fails to start (root path required).

### ISSUE THREAD

**Issue by SheriefAlaa** [HospitalRun/hospitalrun-server#36]
Hospitalrun-server's npm start fails to start (root path required).

NodeJS: 7.4.0
npm: 3.5.2
OS: Ubuntu 16.04

```
~/hospitalrun-server$ npm start

> hospitalrun-server@0.9.17 start /home/ubuntu/hospitalrun-server
> node app.js

/home/ubuntu/hospitalrun-server/node_modules/serve-static/index.js:40
    throw new TypeError('root path required')
    ^

TypeError: root path required
    at Function.serveStatic [as static] (/home/ubuntu/hospitalrun-server/node_modules/serve-static/index.js:40:11)
    at module.exports (/home/ubuntu/hospitalrun-server/node_modules/hospitalrun-server-routes/routes/05-static-routes.js:5:41)
    at /home/ubuntu/hospitalrun-server/node_modules/hospitalrun-server-routes/index.js:5:5
    at Array.forEach (native)
    at module.exports (/home/ubuntu/hospitalrun-server/node_modules/hospitalrun-server-routes/index.js:4:10)
    at Object.<anonymous> (/home/ubuntu/hospitalrun-server/app.js:18:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! hospitalrun-server@0.9.17 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
```

Any ideas what might be causing this?

Thanks.

**Comment by jkleinsc** [comment]
@SheriefAlaa check to see if config.js has the following config value defined:
attachmentsDir: __dirname + '/attachments',

This value was recently added to the example-config.js and is needed by version 0.9.10 of hospitalrun-server-routes.  This was a recent upgrade so if you pulled the latest from git but had an older version of the config file, you will get that error until you add the attachmentsDir config.
