### ISSUE TITLE
Error getting configurations to update & Error creating push database

### ISSUE THREAD

**Issue by chinmaybhatk** [HospitalRun/hospitalrun-server#50]
i could install and run couchdb but when i try to run the server it throws me this error.
```
HospitalRun server listening on {"address":"::","family":"IPv6","port":3000}
Error getting configurations to update { Error: getaddrinfo ENOTFOUND couchdb couchdb:5984
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  name: 'Error',
  scope: 'socket',
  errid: 'request',
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'couchdb',
  host: 'couchdb',
  port: '5984',
  description: 'getaddrinfo ENOTFOUND couchdb couchdb:5984',
  stacktrace: 
   [ 'Error: getaddrinfo ENOTFOUND couchdb couchdb:5984',
     '    at errnoException (dns.js:28:10)',
     '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)' ] }
Error creating push database! { Error: getaddrinfo ENOTFOUND couchdb couchdb:5984
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  name: 'Error',
  scope: 'socket',
  errid: 'request',
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'couchdb',
  host: 'couchdb',
  port: '5984',
  description: 'getaddrinfo ENOTFOUND couchdb couchdb:5984',
  stacktrace: 
   [ 'Error: getaddrinfo ENOTFOUND couchdb couchdb:5984',
     '    at errnoException (dns.js:28:10)',
     '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)' ] }


```
i am not getting where is the issue.. tried all the posts available but no luck.. please help me what is going wrong..
ubuntu 14.04 32 bit
couchdb 1.6.1
node v7.8.0
npm 4.2.0

**Comment by jkleinsc** [comment]
@chinmaybhatk the config file by default defines the couchdb as being on a host called couchdb.  If you are running the database on the same server as HospitalRun, change the following line (line 2) in config.js from:
```js
var config = {
  couchDbServer: 'couchdb',
```
to:
```js
var config = {
  couchDbServer: 'localhost',
```
