### ISSUE TITLE
elasticsearch_hr Not running

### ISSUE THREAD

**Issue by manikandanndz** [HospitalRun/hospitalrun-server#78]
Hi,

I'm trying to install hopitalrun, but after configuring and running docker, one of the instance is not starting. 

[root@hospital-test ~]# docker ps -a
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                      PORTS                                        NAMES
c27fee3d3ca6        hospitalrun_nginx                                     "/bin/sh -c /etc/n..."   18 hours ago        Up 18 hours                 0.0.0.0:443->443/tcp, 0.0.0.0:8055->80/tcp   hospitalrunserver_nginx_1
92cf1f499ff8        hospitalrun                                           "/bin/sh -c ./entr..."   18 hours ago        Up 18 hours                 3000/tcp                                     hospitalrun
3199800d558f        hospitalrun_logstash                                  "/usr/local/bin/do..."   18 hours ago        Up 18 hours                 5044/tcp, 9600/tcp                           logstash_hr
**8737b5b121ee        docker.elastic.co/elasticsearch/elasticsearch:5.3.1   "/bin/bash bin/es-..."   18 hours ago        Exited (1) 17 seconds ago**                                                elasticsearch_hr
a476796c346a        couchdb:1.6                                           "tini -- /docker-e..."   18 hours ago        Up 18 hours                 0.0.0.0:5985->5984/tcp                       couchdb_hr

All the other except elastricsearch is running fine. While checking logs, it was showing below messages. 

[2017-10-20T10:19:19,933][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to created node environment
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.1.jar:5.3.1]
Caused by: java.lang.IllegalStateException: Failed to created node environment
        at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.1.jar:5.3.1]
        ... 6 more
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_121]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_121]
        at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_121]
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:221) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.node.Node.<init>(Node.java:262) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.1.jar:5.3.1]
        ... 6 more

Can any one help me on this

**Comment by ikandars** [comment]
+1 with this issue
